---
# Utilisateur
rstudio_user: marie
rstudio_password: "{{ vault_rstudio_password }}"

# Block storage
block_storage_device: /dev/sdb
block_storage_mount: /data

# Miniforge / Conda
miniforge_version: "26.1.1-3"
miniforge_install_dir: /opt/miniforge
conda_env_name: bioinfo
r_packages:
  - r-base
  - r-seurat
  - bioconductor-infercnv
  - r-biocmanager
  - jags

# RStudio Server
rstudio_version: "2026.01.2-418"
rstudio_port: 8787

# S3 OVH / rclone
rclone_remote_name: ovh_s3
rclone_bucket: marie-rstudio
rclone_sync_path: /data
